#!/bin/bash
#
# install
# 
#  source $HOME/homestead-boxes/homestead-alias
#

HOMESTEAD_BOXES="$(exec 2>/dev/null;builtin cd -- $(dirname "$0"); unset PWD; /usr/bin/pwd || /bin/pwd || pwd)"

#echo '----'
#echo $HOMESTEAD_BOXES
#echo '----'
alias h5='__homestead_func php5.6'
alias h7='__homestead_func php7'

alias h5_mysql="mysql -h 192.168.10.11 -u homestead -psecret"
alias h5_mysqldump="mysqldump -h 192.168.10.11 -u homestead -psecret"

alias h7_mysql="mysql -h 192.168.10.10 -u homestead -psecret"
alias h7_mysqldump="mysqldump -h 192.168.10.10 -u homestead -psecret"

alias hb='cd $HOMESTEAD_BOXES'

function h_update() {
    (builtin cd $HOMESTEAD_BOXES && git stash && git pull && git stash pop);
}

function __homestead_func() {

    if [[ $2 == "edit" ]]; then
        subl $HOMESTEAD_BOXES/$1/Homestead.yaml;
    elif [[ $2 == "hosts" ]]; then
        (builtin cd $HOMESTEAD_BOXES && hosts homestead php7 php5.6);
    elif [[ $2 == "reboot" ]]; then
        (builtin cd $HOMESTEAD_BOXES/$1 && vagrant reload --provision);
        (builtin cd $HOMESTEAD_BOXES && hosts homestead php7 php5.6);
    else
        (builtin cd $HOMESTEAD_BOXES/$1 && vagrant ${@:2});
    fi

    if [[ $2 == 'up' ]]; then
        if [[ $1 == 'php7' ]]; then
            open 'http://homestead7.app/'
        else
            open 'http://homestead.app/'
        fi

        (builtin cd $HOMESTEAD_BOXES && hosts homestead php7 php5.6);
    fi

    __homestead_update_check;

}

function __homestead_update_check() {
    if (builtin cd $HOMESTEAD_BOXES && git fetch && git status) | grep 'Your branch is behind'; then
        echo '\n\n\n------------------------------------------------------------------------\n';
        echo '\tYour homestead boxes should be updated, "h_update".';
        echo '\n------------------------------------------------------------------------\n\n';
    fi
}

function __update_homestead() {

    builtin cd $HOMESTEAD_BOXES

    if git pull --rebase --stat origin master
    then
    #   printf '%s' "$GREEN"
    #   printf '%s\n' '    __             '
    #   printf '%s\n' '   / /_     ______ '
    #   printf '%s\n' '  / __ \   / __  / '
    #   printf '%s\n' ' / / / /  / /_/ /  '
    #   printf '%s\n' '/_/ /_/  /_ _ _/   '
    #   printf '%s\n' '                   '
      printf "${BLUE}%s\n" "Hooray! homestead-boxes have been updated and/or is at the current version."
    #   printf "${BLUE}${BOLD}%s${NORMAL}\n" "To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh"
    #   printf "${BLUE}${BOLD}%s${NORMAL}\n" "Get your Oh My Zsh swag at:  http://shop.planetargon.com/"
    else
      printf "${RED}%s${NORMAL}\n" 'There was an error updating. Try again later?'
    fi
    
}

function __homestead_vagrant() {
    (builtin cd $HOMESTEAD_BOXES/$1 && vagrant ${@:2});
}