#!/bin/bash
#
# install
# 
#  source $HOME/lmo-homestead-boxes/homestead-alias
#

LMO_HOMESTEAD="$(exec 2>/dev/null;builtin cd -- $(dirname "$0"); unset PWD; /usr/bin/pwd || /bin/pwd || pwd)"

#echo '----'
#echo $LMO_HOMESTEAD
#echo '----'
alias h5='__homestead_func php5.6'
alias h7='__homestead_func php7'

alias lhb='cd $LMO_HOMESTEAD'

function h_update() {
    (builtin cd $LMO_HOMESTEAD && git pull);
}

function __homestead_func() {

    if [[ $2 == "edit" ]]; then
        subl $LMO_HOMESTEAD/$1/Homestead.yaml;
    elif [[ $2 == "hosts" ]]; then
        (builtin cd $LMO_HOMESTEAD && hosts homestead php7 php5.6);
    elif [[ $2 == "reboot" ]]; then
        (builtin cd $LMO_HOMESTEAD/$1 && vagrant reload --provision);
    else
        (builtin cd $LMO_HOMESTEAD/$1 && vagrant ${@:2});
    fi

    if [[ $2 == 'up' ]]; then
        open 'http://homestead.app/'
    fi
}

function __update_homestead() {

    builtin cd $LMO_HOMESTEAD

    if git pull --rebase --stat origin master
    then
    #   printf '%s' "$GREEN"
    #   printf '%s\n' '    __             '
    #   printf '%s\n' '   / /_     ______ '
    #   printf '%s\n' '  / __ \   / __  / '
    #   printf '%s\n' ' / / / /  / /_/ /  '
    #   printf '%s\n' '/_/ /_/  /_ _ _/   '
    #   printf '%s\n' '                   '
      printf "${BLUE}%s\n" "Hooray! lmo-homestead-boxes have been updated and/or is at the current version."
    #   printf "${BLUE}${BOLD}%s${NORMAL}\n" "To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh"
    #   printf "${BLUE}${BOLD}%s${NORMAL}\n" "Get your Oh My Zsh swag at:  http://shop.planetargon.com/"
    else
      printf "${RED}%s${NORMAL}\n" 'There was an error updating. Try again later?'
    fi
    
}

function __homestead_vagrant() {
    (builtin cd $LMO_HOMESTEAD/$1 && vagrant ${@:2});
}